### ISSUE TITLE
Milan's lack of advance C# knowledge

### ISSUE THREAD

**Issue by Reptile25** [forte88/Tafe18S101#2]
I have a roadblock with one.
I have an issue with this, due to me not doing 5C#Mobile in TAFE at the moment (next term i will) i don't have the best knowledge of C# to complete this part of the assignment.

**Comment by ReadyWolf** [comment]
No worries. I have completed my part which has an Update feature i can meet up with you and show you in person what to do and help you out. 

  if (editID != -1) {

                conn.Update(new Appointments()
                {

                    ID = editID,
                    EventName = EName,
                    Location = ELocation,
                    EventDate = FinalEventDate,
                    StartTime = STime,
                    EndTime = ETime

                });

                editID = -1; // this should reset the edit check back to zero

            } else
            {
                conn.Insert(new Appointments()
                {
                    EventName = EName,
                    Location = ELocation,
                    EventDate = FinalEventDate,
                    StartTime = STime,
                    EndTime = ETime

                });

            }

**Comment by Reptile25** [comment]
Thanks a lot Matthew, this helped a lot
