### ISSUE TITLE
David's Stupid Naming Error's 

### ISSUE THREAD

**Issue by forte88** [forte88/Tafe18S101#3]
Hey everyone I had an issue with putting details into the Shopping List table for some reason it wasn't picking up the my shopping list class in the model. 

From further inspection I realised this was an issue with naming!! I have changed the name of the ShoppingList page from ShoppingList.xaml to ShoppingListPage.xaml and this fixed the issue as I also had a class called ShoppingList.

**Comment by ReadyWolf** [comment]
Thanks for the tip. I think Milan had this problem too - its easy to do which is why its important to having some sort of convention when naming your files.
